onping_settings:
  Default: &defaults
    host: "*4" # any IPv4 host
    port: 4321
    approot: "https://www.example.com:4321"
    copyright: Plow 2013
    #analytics: UA-YOURCODE

  Development:
    port: 3000
    approot: "http://localhost:3000"
    <<: *defaults

  Testing:
    <<: *defaults

  Staging:
    <<: *defaults

  Production:
    approot: "https://www.example.com"
    <<: *defaults


