# alarm-state-config:
#    tag: 2000
#    src:
#      almKeySrc:
#        unSText: onping.plowtech.net
#    host: www.aacs-us.com
#    port: 2000

{
	"alarm-state-config" : {
		"tag" : "2000",
		"src" : {
			"almKeySrc" : {
				"unSText" : "onping.plowtech.net"
			}
		},
		"host" : "www.aacs-us.com",
		"port" : 2000
	}
}

